<a href="https://colab.research.google.com/github/ksathperera/MLOM/blob/main/Lab_03_tensorflow_Intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
print(tf.version)

<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.10/dist-packages/tensorflow/_api/v2/version/__init__.py'>


In [2]:
string = tf.Variable("this is a string", tf.string)
number = tf.Variable(324, tf.int16)
floating = tf.Variable(3.567, tf.float64)

In [3]:
print(floating)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=3.567>


In [4]:
tf.rank(number)  #to check the rank/degree of a created number variable

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [6]:
tf.rank(string)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [7]:
tf.rank(floating)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [13]:
rank2_tensor = tf.Variable([[1,2,3], [3, 4,5]], tf.int16)  #there is a 2D array to, let see the dimension of it

In [9]:
tf.rank(rank2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [14]:
rank2_tensor.shape

TensorShape([2, 3])

In [15]:
tensor1 = tf.ones([1,2,3]) # tf.ones() creates a shape [1,2,3] tensor full of ones
tensor2 = tf.reshape(tensor1, [2,3,1]) # reshape existing data to shape [2,3,1]
tensor3 = tf.reshape(tensor2, [3, -1]) # -1 tells the tensor to calculate the size of the dimension in that place and this will reshape the tensor to [3,3]

In [16]:
#Now let's have a look at our different tensors
print(tensor1)
print(tensor2)
print(tensor3)


tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


In [19]:
#creating a 2D tensor
matrix = [[1,2,3,4,5],
[6,7,8,9,10],
[11,12,13,14,15],
[16,17,18,19,20]]

#shape = [4,5] since there is a 2 dimension matrix

tensor = tf.Variable(matrix, dtype=tf.int32)  #create a variable and assign matrix for that variable
print(tf.rank(tensor))
print(tensor.shape)

tf.Tensor(2, shape=(), dtype=int32)
(4, 5)


In [20]:
three = tensor[0,2] # selects the 3rd element from the 1st row
print(three) # -> 3

tf.Tensor(3, shape=(), dtype=int32)


In [21]:
row1 = tensor[0] # selects the first row
print(row1)

tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)


In [22]:
column1 = tensor[:, 0] # selects the first column
print(column1)


tf.Tensor([ 1  6 11 16], shape=(4,), dtype=int32)


In [23]:
column_1_in_row_2_and_3 = tensor[1:3, 0]
print(column_1_in_row_2_and_3)

tf.Tensor([ 6 11], shape=(2,), dtype=int32)
